package com.hr.nipuream.gz.dao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hr.nipuream.gz.controller.main.bean.GZbean;

import com.hr.nipuream.gz.dao.db.GZbeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gZbeanDaoConfig;

    private final GZbeanDao gZbeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gZbeanDaoConfig = daoConfigMap.get(GZbeanDao.class).clone();
        gZbeanDaoConfig.initIdentityScope(type);

        gZbeanDao = new GZbeanDao(gZbeanDaoConfig, this);

        registerDao(GZbean.class, gZbeanDao);
    }
    
    public void clear() {
        gZbeanDaoConfig.getIdentityScope().clear();
    }

    public GZbeanDao getGZbeanDao() {
        return gZbeanDao;
    }

}
